//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmsPoView
    {
        public string poNo { get; set; }
        public long id { get; set; }
        public int supplierId { get; set; }
        public Nullable<int> status { get; set; }
        public string categoryName { get; set; }
        public Nullable<int> totalSku { get; set; }
        public Nullable<int> totalPrepoAmount { get; set; }
        public string creator { get; set; }
        public Nullable<int> skuPriceType { get; set; }
        public Nullable<System.DateTime> preArrivalTime2 { get; set; }
        public Nullable<System.DateTime> arrivalTime2 { get; set; }
        public Nullable<System.DateTime> expairTime2 { get; set; }
        public Nullable<System.DateTime> ctime2 { get; set; }
        public Nullable<System.DateTime> utime2 { get; set; }
        public string @operator { get; set; }
        public string poiname { get; set; }
        public int poiId { get; set; }
        public string StatusName { get; set; }
    }
}
