//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingNoteItemView
    {
        public Nullable<System.DateTime> cDate { get; set; }
        public long skuId { get; set; }
        public string poNo { get; set; }
        public string spuName { get; set; }
        public string skuSpec { get; set; }
        public string skuDictUnitName { get; set; }
        public Nullable<decimal> prePoAmount { get; set; }
        public Nullable<decimal> poAmount { get; set; }
        public Nullable<decimal> sumPoPrice { get; set; }
        public Nullable<System.Guid> RnId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ContrastPrice { get; set; }
        public Nullable<decimal> ContrastGrossProfit { get; set; }
        public string Supplier { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<decimal> ReturnPrice { get; set; }
        public string Remark { get; set; }
        public long id { get; set; }
    }
}
