//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceivingNote()
        {
            this.RnPoItems = new HashSet<RnPoItem>();
        }
    
        public System.Guid RnId { get; set; }
        public long skuId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ContrastPrice { get; set; }
        public Nullable<decimal> ContrastGrossProfit { get; set; }
        public string Supplier { get; set; }
        public bool PaymentStatus { get; set; }
        public Nullable<decimal> ApplyQuantity { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string @operator { get; set; }
        public System.DateTime cDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RnPoItem> RnPoItems { get; set; }
    }
}
