//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RnPoItem
    {
        public System.Guid RnId { get; set; }
        public string poNo { get; set; }
        public decimal Quantity { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
