//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        public long skuId { get; set; }
        public string poNo { get; set; }
        public string categoryName { get; set; }
        public string spuName { get; set; }
        public string skuMallCode { get; set; }
        public string skuCode { get; set; }
        public Nullable<int> storageTemperatureLevel { get; set; }
        public Nullable<int> guaranteePeriod { get; set; }
        public string skuSpec { get; set; }
        public Nullable<int> skuCostPrice { get; set; }
        public string skuDictUnitName { get; set; }
        public Nullable<decimal> skuBoxQuantity { get; set; }
        public Nullable<decimal> prePoAmount { get; set; }
        public Nullable<decimal> poAmount { get; set; }
        public Nullable<long> productionDate { get; set; }
        public Nullable<decimal> sumPrePoPrice { get; set; }
        public Nullable<decimal> sumPoPrice { get; set; }
        public Nullable<int> unitId { get; set; }
        public Nullable<int> packageType { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<int> guaranteePeriodType { get; set; }
        public Nullable<decimal> availableQuantity { get; set; }
        public Nullable<decimal> availablePoPrice { get; set; }
        public Nullable<System.DateTime> productionDate2 { get; set; }
        public System.DateTime cTime2 { get; set; }
    }
}
