//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsByDaySku
    {
        public string date { get; set; }
        public long skuId { get; set; }
        public string spuName { get; set; }
        public string poAmount { get; set; }
        public Nullable<decimal> sumPoPrice2 { get; set; }
    }
}
