//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsByDailySkuPoi
    {
        public string date { get; set; }
        public string poiName { get; set; }
        public long skuid { get; set; }
        public string spuName { get; set; }
        public string skuSpec { get; set; }
        public string skuDictUnitName { get; set; }
        public Nullable<decimal> prePoAmount { get; set; }
        public string pkey { get; set; }
    }
}
