//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDataDownloader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StockEntities : DbContext
    {
        public StockEntities()
            : base("name=StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_UpdateStockOperationStatus(Nullable<System.Guid> id, Nullable<int> action, Nullable<int> status, string content, string message, Nullable<int> elapsedMilliseconds)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var elapsedMillisecondsParameter = elapsedMilliseconds.HasValue ?
                new ObjectParameter("elapsedMilliseconds", elapsedMilliseconds) :
                new ObjectParameter("elapsedMilliseconds", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateStockOperationStatus", idParameter, actionParameter, statusParameter, contentParameter, messageParameter, elapsedMillisecondsParameter);
        }
    
        public virtual ObjectResult<usp_GetSummaryDateListByCode_Result> usp_GetSummaryDateListByCode(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("stockCode", stockCode) :
                new ObjectParameter("stockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSummaryDateListByCode_Result>("usp_GetSummaryDateListByCode", stockCodeParameter);
        }
    
        public virtual int usp_SaveStockSummary(string stockSummaryXml)
        {
            var stockSummaryXmlParameter = stockSummaryXml != null ?
                new ObjectParameter("stockSummaryXml", stockSummaryXml) :
                new ObjectParameter("stockSummaryXml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SaveStockSummary", stockSummaryXmlParameter);
        }
    
        public virtual ObjectResult<usp_GetDetailDateListByCode_Result> usp_GetDetailDateListByCode(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("stockCode", stockCode) :
                new ObjectParameter("stockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDetailDateListByCode_Result>("usp_GetDetailDateListByCode", stockCodeParameter);
        }
    
        public virtual int usp_UpdateStockSummaryStatus(Nullable<System.Guid> id, Nullable<int> status, string content, Nullable<int> elapsedMilliseconds)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var elapsedMillisecondsParameter = elapsedMilliseconds.HasValue ?
                new ObjectParameter("elapsedMilliseconds", elapsedMilliseconds) :
                new ObjectParameter("elapsedMilliseconds", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateStockSummaryStatus", idParameter, statusParameter, contentParameter, elapsedMillisecondsParameter);
        }
    
        public virtual int usp_SaveStockDetail(string stockDetailSql, Nullable<System.DateTimeOffset> actionDate, string stockCode, Nullable<int> batchNumber)
        {
            var stockDetailSqlParameter = stockDetailSql != null ?
                new ObjectParameter("stockDetailSql", stockDetailSql) :
                new ObjectParameter("stockDetailSql", typeof(string));
    
            var actionDateParameter = actionDate.HasValue ?
                new ObjectParameter("actionDate", actionDate) :
                new ObjectParameter("actionDate", typeof(System.DateTimeOffset));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("stockCode", stockCode) :
                new ObjectParameter("stockCode", typeof(string));
    
            var batchNumberParameter = batchNumber.HasValue ?
                new ObjectParameter("batchNumber", batchNumber) :
                new ObjectParameter("batchNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SaveStockDetail", stockDetailSqlParameter, actionDateParameter, stockCodeParameter, batchNumberParameter);
        }
    }
}
