//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfo
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTimeOffset> ListingDate { get; set; }
        public string CompanyInfo { get; set; }
        public string Category { get; set; }
        public System.DateTimeOffset LastUpdateTime { get; set; }
        public string CapitalStructure { get; set; }
        public System.Guid Id { get; set; }
    }
}
